# Generated by Django 6.0 on 2025-12-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_project_task'),
        ('base_app', '0003_populate_initial_data'),
    ]

    operations = [
    ]
